V8bshage/Controllers/ShopController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using V8bshage.Data;
using V8bshage.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Http;
using System.IO;

namespace V8bshage.Controllers
{
    public class ShopController : Controller
    {
        private readonly AdvertisementContext _adb;

        private readonly UserManager<User> _userManager;

        public ShopController(AdvertisementContext adb, UserManager<User> userManager)
        {
            _adb = adb;
            _userManager = userManager;
        }

        [Authorize]
        public IActionResult Index()
        {
            IEnumerable<Advertisement> advList = _adb.Advertisements;
            return View(advList);
        }

        public IActionResult Create()
        {
            return View();
        }

        private Task<User> GetCurrentUserAsync() => _userManager.GetUserAsync(HttpContext.User);

        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Advertisement adv)
        {
            if(ModelState.IsValid)
            {
                var user = await GetCurrentUserAsync();

                Advertisement new_adv = new Advertisement
                {
                    Title = adv.Title,
                    Description = adv.Description,
                    Price = adv.Price,
                    UserId = user.Id
                };

                if (Request.Form.Files.Count > 0)
                {
                    IFormFile file = Request.Form.Files.FirstOrDefault();
                    using (var dataStream = new MemoryStream())
                    {
                        await file.CopyToAsync(dataStream);
                        new_adv.Photo = dataStream.ToArray();
                    }
                } else
                {
                    string storePath = "wwwroot/img/";
                    var path = Path.Combine(Directory.GetCurrentDirectory(), storePath, "default_adv.png");

                    using (FileStream fs = new FileStream(path, FileMode.Open, FileAccess.Read))
                    {
                        // Create a byte array of file stream length
                        byte[] bytes = System.IO.File.ReadAllBytes(path);
                        //Read block of bytes from stream into the byte array
                        fs.Read(bytes, 0, System.Convert.ToInt32(fs.Length));
                        //Close the File Stream
                        fs.Close();

                        new_adv.Photo = bytes;
                    }

                }

                _adb.Advertisements.Add(new_adv);
                await _adb.SaveChangesAsync();

                return RedirectToAction("Index");
            }

            return View(adv);
        }

        [HttpGet]
        public async Task<IActionResult> Info(int id)
        {
            var adv = _adb.Advertisements.Find(id);
            var user = await GetCurrentUserAsync();

            AdvInfoViewModel model = new AdvInfoViewModel
            {
                Adv = adv,
                User = user
            };

            return View(model);
        }
    }
}

V8bshage/Views/Shop/Create.cshtml
@model V8bshage.Models.Advertisement

<form method="post" asp-action="Create" enctype="multipart/form-data">
    <div class="border p-3">
        <div class="form-group row">
            <h2>Добавить объявление</h2>
        </div>
        <div class="row">
            <div class="col-12">
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="Title"></label>
                    </div>
                    <div class="col-4">
                        <label asp-for="Description"></label>
                    </div>
                    <div class="col-4">
                        <label asp-for="Price"></label>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-4">
                        <input asp-for="Title" class="form-control">
                    </div>
                    <div class="col-4">
                        <input asp-for="Description" class="form-control">
                    </div>
                    <div class="col-4">
                        <input asp-for="Price" class="form-control">
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="Photo"></label>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-4">
                        <input asp-for="Photo" type="file" class="form-control">
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-8 offset-2 row">
                        <div class="col">
                            <input type="submit" class="btn btn-primary w-75" value="Создать">
                        </div>
                        <div class="col">
                            <a asp-action="Index" class="btn btn-danger w-75">Назад</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>

V8bshage/Views/Shop/Index.cshtml
@model IEnumerable<V8bshage.Models.Advertisement>

<link href="css/cards.css" rel="stylesheet" />

<div class="container p-3">
    <div class="row pt-4">
        <div class="col-6">
            <h1>Объявления</h1>
        </div>
        <div class="col-6 text-right">
            <a class="btn btn-primary" asp-controller="Shop" asp-action="Create">Добавить объявление</a>
        </div>
    </div>
    <div class="flex-container">
        @if (Model.Count<Advertisement>() > 0)
        {
            @foreach (var adv in Model)
            {
                <div class="card" style="width: 18rem;">
                    <img class="card-img-top" style="object-fit:contain; width:250px; height:250px" src="data:image/jpeg;base64,@(Convert.ToBase64String(adv.Photo))" />
                    <div class="card-body">
                        <h5 class="card-title">@adv.Title</h5>
                        <p class="card-text">@adv.Description</p>
                        <a asp-controller="Shop" asp-action="Info" asp-route-id="@adv.AdvId" class="btn btn-primary">Подробнее</a>
                    </div>
                </div>
            }
        }
        else
        {
            <p>Ещё нет никаких объявлений</p>
        }
    </div>
</div>

V8bshage/Views/Shop/Info.cshtml
@model V8bshage.Models.AdvInfoViewModel

<link rel="stylesheet" src="css/profile" />

<h1>@Model.Adv.Title</h1>
<img class="card-img-top" style="object-fit:contain; width:200px; height:300px;" src="data:image/jpeg;base64,@(Convert.ToBase64String(Model.Adv.Photo))" />
<p>@Model.Adv.Description</p>
<p>@Model.Adv.Price</p>

<a href=@Model.User.Vk>
    <img src="img/vk.png" class="user-profile-image rounded-circle" />
</a>
<a href=@Model.User.Telegram>
    <img src="img/tg.png" class="user-profile-image rounded-circle" />
</a>