V8bshage/Models/News.cs
using System;
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Http;

namespace V8bshage.Models
{
    public class News
    {
        public Guid Id { get; set; }

        [Required]
        [Display(Name = "Заголовок")]
        public string Title { get; set; }

        [Required]
        [Display(Name ="Описание")]
        public string Summary { get; set; }

        [Display(Name = "Фото")]
        public byte[] Photo { get; set; }

        [DataType(DataType.DateTime)]
        public DateTime PostTime { get; set; }
    }
}

V8bshage/Models/NewsViewModel.cs
using System;
using Microsoft.AspNetCore.Http;

namespace V8bshage.Models
{
    public class NewsViewModel
    {
        public string Title { get; set; }
        public string Summary { get; set; }
        public IFormFile Photo { get; set; }

        public DateTime PostTime { get; set; }
    }
}

V8bshage/Controllers/NewsController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using V8bshage.Data;
using V8bshage.Models;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;

namespace V8bshage.Controllers
{
    public class NewsController : Controller
    {
        private readonly NewsContext _context;
        private IWebHostEnvironment _appEnvironment;

        public NewsController(NewsContext context, IWebHostEnvironment appEnvironment)
        {
            _context = context;
            _appEnvironment = appEnvironment;
        }

        // GET: News
        [Authorize]
        public async Task<IActionResult> Index()
        {
            return View(await _context.News.ToListAsync());
        }

        // GET: News/Details/5
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var news = await _context.News
                .FirstOrDefaultAsync(m => m.Id == id);
            if (news == null)
            {
                return NotFound();
            }

            return View(news);
        }

        // GET: News/Create
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Guid id, [Bind("Id,Title,Summary,PostTime,Photo")] NewsViewModel new_news)
        {
            if (ModelState.IsValid)
            {
                News news = new News { Id = Guid.NewGuid(), Title = new_news.Title, Summary = new_news.Summary, PostTime = DateTime.Now };

                if (new_news.Photo != null)
                {
                    byte[] imageData = null;
                    // считываем переданный файл в массив байтов
                    using (var binaryReader = new BinaryReader(new_news.Photo.OpenReadStream()))
                    {
                        imageData = binaryReader.ReadBytes((int)new_news.Photo.Length);
                    }
                    // установка массива байтов
                    news.Photo = imageData;
                    Console.WriteLine(imageData);
                }

                _context.Add(news);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return RedirectToAction("Index");
        }

        // GET: News/Edit/5
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var news = await _context.News.FindAsync(id);
            if (news == null)
            {
                return NotFound();
            }
            return View(news);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, [Bind("Id,Title,Summary,PostTime")] News news)
        {
            if (id != news.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(news);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!NewsExists(news.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(news);
        }

        // GET: News/Delete/5
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var news = await _context.News
                .FirstOrDefaultAsync(m => m.Id == id);
            if (news == null)
            {
                return NotFound();
            }

            return View(news);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            var news = await _context.News.FindAsync(id);
            _context.News.Remove(news);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool NewsExists(Guid id)
        {
            return _context.News.Any(e => e.Id == id);
        }

        public async Task<IActionResult> Info(Guid id)
        {
            var post = await _context.News.FindAsync(id);
            return View(post);
        }
    }
}

V8bshage/Views/News/Create.cshtml
@model V8bshage.Models.News

@{
    ViewData["Title"] = "Create";
}

<h1>Предложить новость</h1>

<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" method="post" enctype="multipart/form-data">
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="Summary" class="control-label"></label>
                <input asp-for="Summary" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="Photo" class="control-label"></label>
                <input asp-for="Photo" type="file"/>
                <span asp-validation-for="Photo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Предложить" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

V8bshage/Views/News/Delete.cshtml
@model V8bshage.Models.News

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>News</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Summary)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Summary)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PostTime)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PostTime)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

V8bshage/Views/News/Edit.cshtml
@model V8bshage.Models.News

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>News</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Summary" class="control-label"></label>
                <input asp-for="Summary" class="form-control" />
                <span asp-validation-for="Summary" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PostTime" class="control-label"></label>
                <input asp-for="PostTime" class="form-control" />
                <span asp-validation-for="PostTime" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

V8bshage/Views/News/Index.cshtml
@model IEnumerable<V8bshage.Models.News>


<link href="css/news.css" rel="stylesheet" />

<section class="grid">
    @foreach (var news in Model)
    {
        <article class="grid-item">
            <div class="image">
                <img src="data:image/jpeg;base64,@(Convert.ToBase64String(news.Photo))" />
            </div>
            <div class="info">
                <h2>@news.Title</h2>
                <div class="button-wrap">
                    <a class="atuin-btn" asp-controller="News" asp-action="Info">Подробнее</a>
                </div>
            </div>
        </article>
    }
</section>

V8bshage/Views/News/Info.cshtml
@model V8bshage.Models.News

<link rel="stylesheet" src="css/profile" />

<h1>@Model.Title</h1>
<img class="card-img-top" style="object-fit:contain; width:200px; height:300px;" src="data:image/jpeg;base64,@(Convert.ToBase64String(Model.Photo))" />
<p>@Model.Summary</p>
<p>@Model.PostTime</p>